name: Main Branch Build
on:
  push:
    branches:
      - main

jobs:
  package-bundle:
    runs-on: ubuntu-latest
    environment: prod
    name: Package ues.io bundle
    steps:
      - name: Setup Uesio CLI Symlink
        shell: bash
        run: |
          # Symlink the Uesio CLI for subsequent use
          wget -q https://github.com/ues-io/uesio/releases/download/v0.7.0/uesio-linux
          chmod +x uesio-linux
          sudo ln -s $PWD/uesio-linux /usr/local/bin/uesio
      - name: Run help command
        shell: bash
        run: |
          uesio help
      - name: Deploy
        shell: bash
        env:
          UESIO_CLI_USERNAME: ${{ secrets.UESIO_CLI_USERNAME || '' }}
          UESIO_CLI_PASSWORD: ${{ secrets.UESIO_CLI_PASSWORD }}
          UESIO_CLI_HOST: ${{ vars.UESIO_CLI_HOST }}
        run: |
          # Login to uesio instance
          uesio login
