name: Main Branch Build
on:
  push:
    branches:
      - main

jobs:
  package-bundle:
    runs-on: ubuntu-latest
    environment: prod
    name: Package ues.io bundle
    steps:
      - uses: actions/checkout@v4
      - name: Setup Uesio CLI Symlink
        shell: bash
        run: |
          # Symlink the Uesio CLI for subsequent use
          wget -q https://github.com/ues-io/uesio/releases/download/v0.7.0/uesio-linux
          chmod +x uesio-linux
          sudo ln -s $PWD/uesio-linux /usr/local/bin/uesio
      - name: Run help command
        shell: bash
        run: |
          uesio help
      - name: Deploy
        shell: bash
        env:
          UESIO_CLI_USERNAME: ${{ secrets.UESIO_CLI_USERNAME || '' }}
          UESIO_CLI_PASSWORD: ${{ secrets.UESIO_CLI_PASSWORD }}
          UESIO_CLI_HOST: ${{ vars.UESIO_CLI_HOST }}
        run: |
          # Login to uesio instance
          uesio login

          # Set the current workspace
          uesio work -n=dev

          # Deploy this code to the workspace
          uesio deploy

          # Create a new patch bundle
          patchResult=$(uesio bundle create -t=patch)

          # Extract version number from patchResult variable using grep
          version=$(echo "$patchResult" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

          # Set the active site to prod
          uesio siteadmin -n=prod

          # Update the prod site to the newly created version
          uesio site use -b=$version
